FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

COPY gradlew .
COPY gradle gradle

COPY build.gradle .
COPY settings.gradle .

RUN chmod +x gradlew
RUN ./gradlew build -x test --warning-mode all || true

COPY . .

CMD ["./gradlew", "bootRun", "--continuous"]
